# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

# Default build settings
[build]
  publish = "public"
  command = "git submodule update -f --init --recursive && npm install && hugo"

[build.environment]
  HUGO_VERSION = "0.111.1"

[context.production.environment]
  HUGO_ENV = "production"
