# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

# Default build settings
[build]
  publish = "public"

[build.environment]
HUGO_VERSION = "0.104.3"
GO_VERSION = "1.19.2"

[context.production.environment]
  HUGO_ENV = "production"
